pipeline{
    agent {
	    kubernetes {
            cloud 'kubernetes'
            label 'maven'
            yaml '''
            apiVersion: v1
            kind: Pod
            spec:
              containers:
                - name: maven
                  image: maven:3.8.1-openjdk-15
                  command:
                    - cat
                  tty: true
            '''
	    }
	}

    stages{
        stage('Checkout Git') {
            steps {
                 git branch: 'develop', url:'https://github.com/AndriyPyzh/Rentler.git'
            }
        }
        stage("Build") {
    		steps {
        		container('maven') {
        		    withCredentials([file(credentialsId: 'gcloud-creds', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                        sh "mvn clean package -DskipTests -Pdev -f rentler-helper/pom.xml"
        		    }
                }
    		}
        }
        stage("Test") {
    		steps {
        		container('maven') {
        		    withCredentials([file(credentialsId: 'gcloud-creds', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                        sh "mvn verify -Pdev -f rentler-helper/pom.xml"
        		    }
                }
    		}
        }
        stage("Install") {
    		steps {
        		container('maven') {
        		    withCredentials([file(credentialsId: 'gcloud-creds', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                        sh "mvn deploy -DskipTests -Pdev -f rentler-helper/pom.xml"
                    }
                }
    		}
        }
    }
}

